# Generated by Django 5.1.4 on 2025-01-09 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Движение денежных средств',
                'verbose_name_plural': 'Движения денежных средств',
            },
        ),
        migrations.CreateModel(
            name='CashflowCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория ДДС',
                'verbose_name_plural': 'Категории ДДС',
            },
        ),
        migrations.CreateModel(
            name='CashflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус ДДС',
                'verbose_name_plural': 'Статусы ДДС',
            },
        ),
        migrations.CreateModel(
            name='CashflowType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип ДДС',
                'verbose_name_plural': 'Тип ДДС',
            },
        ),
        migrations.CreateModel(
            name='CashflowSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashflow_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflows.cashflowcategory', verbose_name='Категория ДДС')),
            ],
            options={
                'verbose_name': 'Подкатегория ДДС',
                'verbose_name_plural': 'Подкатегории ДДС',
            },
        ),
        migrations.AddField(
            model_name='cashflowcategory',
            name='cashflow_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflows.cashflowtype', verbose_name='Тип ДДС'),
        ),
    ]
