# Generated by Django 5.1.4 on 2025-01-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'verbose_name': 'Движение денежных средств', 'verbose_name_plural': 'ДДС'},
        ),
        migrations.AddField(
            model_name='cashflowsubcategory',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
