# Generated by Django 5.1.4 on 2025-01-09 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflows', '0002_alter_cashflow_options_cashflowsubcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='cashflow_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cashflows.cashflowcategory', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflow',
            name='cashflow_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cashflows.cashflowstatus', verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflow',
            name='cashflow_subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cashflows.cashflowsubcategory', verbose_name='Подкатегория'),
            preserve_default=False,
        ),
    ]
