# Generated by Django 5.1.4 on 2025-01-09 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflows', '0003_cashflow_cashflow_category_cashflow_cashflow_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflowcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='cashflowstatus',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='cashflowsubcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='cashflowtype',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Тип'},
        ),
        migrations.AddField(
            model_name='cashflow',
            name='cashflow_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cashflows.cashflowtype', verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
