# Generated by Django 5.1.4 on 2025-01-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflows', '0004_alter_cashflowcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
