# Generated by Django 5.1.4 on 2025-01-10 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflows', '0005_alter_cashflow_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'ordering': ['-date'], 'verbose_name': 'Движение денежных средств', 'verbose_name_plural': 'ДДС'},
        ),
    ]
