# Generated by Django 5.1.4 on 2025-01-10 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflows', '0007_alter_cashflow_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Движение денежных средств', 'verbose_name_plural': 'ДДС'},
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='date',
        ),
        migrations.AddField(
            model_name='cashflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
