# Generated by Django 5.1.4 on 2025-01-14 08:54

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HR_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
        migrations.CreateModel(
            name='HR_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='TimezoneDifference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference', models.SmallIntegerField(verbose_name='Разница во времени')),
            ],
            options={
                'verbose_name': 'Разница во времени',
                'verbose_name_plural': 'Разница во времени',
            },
        ),
        migrations.CreateModel(
            name='HR_Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Возраст')),
                ('portfolio_link', models.URLField(max_length=500, verbose_name='Ссылка на портфолио')),
                ('request_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата отклика')),
                ('test_task_given_datetime', models.DateTimeField(verbose_name='Дата, когда кандидату было дано тестовое задание')),
                ('test_task_completed_datetime', models.DateTimeField(verbose_name='Дата выполнения тестового задания')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.hr_position', verbose_name='Позиция')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.hr_status', verbose_name='Статус')),
                ('time_difference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.timezonedifference', verbose_name='Разница во времени')),
            ],
        ),
    ]
