# Generated by Django 5.1.4 on 2025-01-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_rename_request_datetime_hr_candidate_requested_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hr_candidate',
            options={'verbose_name': 'Кандидат', 'verbose_name_plural': 'Кандидаты'},
        ),
        migrations.AlterField(
            model_name='hr_candidate',
            name='portfolio_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на портфолио'),
        ),
    ]
