# Generated by Django 5.1.4 on 2025-01-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_hr_candidate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_candidate',
            name='test_task_completed_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения тестового задания'),
        ),
    ]
