# Generated by Django 5.1.4 on 2025-01-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_hr_candidate_test_task_completed_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_candidate',
            name='completed_test_task_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на выполненное тестовое задание'),
        ),
    ]
